Repository owncloud/client, pull requests merged in 2018-05, with the labels that each got.

#6502 Correct incorrect reference to OSX Menu bar
  doc/navigating.rst
Labels: Documentation

#6526 macOS: Don't use WAL for sqlite3 in /Volumes
  src/common/syncjournaldb.cpp
Labels: bug

#6556 Fix make doc-man in shadow build
  man/CMakeLists.txt
Labels: Documentation

#6558 Virtual files: Only remove virtual file once on download
  src/csync/csync_reconcile.cpp
  test/testsyncvirtualfiles.cpp
Labels: Virtual Files

#6552 Share dialog: use the original name and not the virtual file name
  src/gui/sharedialog.cpp
  src/gui/socketapi.cpp
  src/gui/socketapi.h
Labels: Virtual Files

#6559 Virtual files: Wipe virtual after download completes, not before
  src/libsync/propagatedownload.cpp
  test/testsyncvirtualfiles.cpp
Labels: Virtual Files

#6551 Virtual Files: Allow to download a folder recursively from the socketAPI
  src/common/syncjournaldb.cpp
  src/common/syncjournaldb.h
  src/gui/folder.cpp
  src/gui/folder.h
  src/gui/socketapi.cpp
  test/testsyncvirtualfiles.cpp
Labels: Virtual Files
