Repository owncloud/client, pull requests merged in 2018-04, with the labels that each got.

#6377 Notify if an explicitly excluded folder is created
  src/gui/folder.cpp
  src/gui/folder.h
Labels: ReadyToTest

#6425 Deltasync: Use native API for opening files on Windows
  src/libsync/propagatecommonzsync.cpp
Labels: Delta-sync

#6441 Doc: Explaining conflict files and resolving them
  doc/conflicts.rst
  doc/index.rst
Labels: Documentation

#6450 macOS: Implement new dynamic Finder menu items #6328
  shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/FinderSync.h
  shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/FinderSync.m
  shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/SyncClientProxy.h
  shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/SyncClientProxy.m
  src/gui/socketapi.cpp
Labels: ReadyToTest, gold-ticket

#6453 Notifications: Also have clickable link #6236
  src/gui/activitydata.h
  src/gui/notificationwidget.cpp
Labels: ReadyToTest

#6423 Documentation: Update building.rst #6154 #5594
  doc/building.rst
Labels: Documentation

#6470 Wizard: Move the 'Skip folder configuration' in a radio button
  src/gui/owncloudsetupwizard.cpp
  src/gui/owncloudsetupwizard.h
  src/gui/wizard/owncloudadvancedsetuppage.cpp
  src/gui/wizard/owncloudadvancedsetuppage.h
  src/gui/wizard/owncloudadvancedsetuppage.ui
  src/gui/wizard/owncloudwizard.cpp
  src/gui/wizard/owncloudwizard.h
Labels: gold-ticket
