Repository owncloud/client, pull requests merged in 2019-01, with the labels that each got.

#6935 vfs: Remove newFilesAreVirtual - use root PinState instead
  src/common/syncjournaldb.cpp
  src/common/syncjournaldb.h
  src/gui/accountsettings.cpp
  src/gui/folder.cpp
  src/gui/folder.h
  src/gui/folderman.cpp
  src/gui/owncloudsetupwizard.cpp
  src/libsync/discovery.cpp
  src/libsync/discovery.h
  src/libsync/discoveryphase.cpp
  src/libsync/syncoptions.h
  test/testsyncjournaldb.cpp
  test/testsyncvirtualfiles.cpp
Labels: Virtual Files

#6962 Fix discovery crash when non-virtual but suffixed files exist on server or in db
  src/libsync/discovery.cpp
  test/testsyncvirtualfiles.cpp
Labels: DO NOT MERGE YET

#6976 vfs: Update pinning context menu to be less confusing
  src/gui/socketapi.cpp
Labels: Virtual Files

#6969 Remove unrequired start attribute
  docs/modules/ROOT/pages/building.adoc
Labels: Documentation, Enhancement
