Repository owncloud/client, pull requests merged in 2019-03, with the labels that each got.

#7067 OwnSql: Distinguish no-data from error
  ChangeLog
  src/common/ownsql.cpp
  src/common/ownsql.h
  src/common/syncjournaldb.cpp
  test/testownsql.cpp
  test/testpermissions.cpp
Labels: gold-ticket

#7094 macOS: Fix vfs suffix plugin paths #7090
  CMakeLists.txt
  admin/osx/macdeployqt.py
  src/libsync/vfs/suffix/CMakeLists.txt
Labels: gold-ticket

#7091 Doc: Add faq entry for changing server url
  docs/modules/ROOT/pages/faq.adoc
Labels: Documentation

#7097 [#603] - Remove merge conflict markers in the troubleshooting appendix
  docs/modules/ROOT/pages/troubleshooting.adoc
Labels: Documentation, Enhancement, bug

#7099 Fix issues in the architecture page
  docs/modules/ROOT/examples/architecture/cloud-capabilities-json-response.json
  docs/modules/ROOT/pages/architecture.adoc
Labels: Documentation, Enhancement, bug
