Repository owncloud/client, pull requests merged in 2019-09, with the labels that each got.

#7440 Propagator: Delay job execution a bit #7439
  src/libsync/owncloudpropagator.cpp
Labels: DO NOT MERGE YET

#7454 Fix incorrect AsciiDoc attribute references in docs
  docs/modules/ROOT/pages/building.adoc
Labels: Documentation, p4-low

#7461 Reconcile: Sort already during discovery #7445
  src/libsync/syncengine.cpp
Labels: sev2-high

#7462 Discovery: List local directories from thread #7456 #7439
  src/libsync/discovery.cpp
  src/libsync/discovery.h
  src/libsync/discoveryphase.cpp
  src/libsync/discoveryphase.h
  test/testsyncengine.cpp
Labels: Performance, sev2-high
