Repository owncloud/client, pull requests merged in 2019-10, with the labels that each got.

#7510 Update docs JavaScript dependencies
  docs/yarn.lock
Labels: Documentation, dependencies

#6914 Wizard: do not display HTML error page from the server in a message box
  src/gui/owncloudsetupwizard.cpp
Labels: Design & UX

#7520 Fix several broken links
  docs/modules/ROOT/pages/architecture.adoc
  docs/modules/ROOT/pages/navigating.adoc
  docs/modules/ROOT/pages/troubleshooting.adoc
  docs/modules/ROOT/pages/visualtour.adoc
Labels: Documentation
