Repository owncloud/client, pull requests merged in 2020-03, with the labels that each got.

#7804 Fix crash reporter in craft
  src/cmd/CMakeLists.txt
  src/crashreporter/CMakeLists.txt
Labels: DO NOT MERGE YET

#7821 Add the missing documentation content to the PDF configuration file
  docs/books/ownCloud_Desktop_Client_Manual.adoc
Labels: Documentation, bug

#7827 Add the missing content to the PDF configuration file
  docs/books/ownCloud_Desktop_Client_Manual.adoc
Labels: Documentation
