Repository owncloud/client, pull requests merged in 2021-12, with the labels that each got.

#9254 reduce time waiting for password box
  test/gui/shared/scripts/pageObjects/AccountConnectionWizard.py
Labels: QA:team

#9232 Fix TestLogParser for scenario outline tests
  test/gui/TestLogParser.py
  test/gui/tst_syncing/test.feature
Labels: QA:team

#9266 Fix hiding of activity tab in case app is disabled or not installed
  changelog/unreleased/9266
  src/gui/models/activitylistmodel.cpp
Labels: bug, Server Involved

#9272 use qt5.12 squish for UI tests
  .drone.star
Labels: QA:team

#9279 [tests-only] Bump middleware commit id to the latest
  .drone.env
Labels: QA:team

#9188 [tests-only] added tests for multiuser share
  test/gui/shared/scripts/pageObjects/SharingDialog.py
  test/gui/shared/steps/steps.py
  test/gui/tst_sharing/test.feature
Labels: QA:team

#9286 Ensure we compare the correct signals
  src/common/syncfilestatus.cpp
  src/common/syncfilestatus.h
  test/testsyncfilestatustracker.cpp
Labels: p1-urgent

#9288 [tests-only]Skipped 3 failed tests
  .drone.star
  test/gui/tst_syncing/test.feature
Labels: QA:team

#9280 [Tests-Only] add test for folder sync
  test/gui/tst_syncing/test.feature
Labels: QA:team

#9258 [tests-only]Added tests for folder creation and syncing (part 2)
  test/gui/tst_syncing/test.feature
Labels: QA:team

#9282 [tests-only]Add sharing test
  test/gui/tst_sharing/test.feature
Labels: QA:team

#9090 Fix wrong status displayed for files moved on the server
  changelog/unreleased/9071
  src/libsync/filesystem.cpp
  src/libsync/owncloudpropagator.cpp
  src/libsync/syncengine.cpp
  src/libsync/syncfileitem.cpp
  src/libsync/syncfileitem.h
  test/testsyncconflict.cpp
  test/testsyncfilestatustracker.cpp
  test/testsyncvirtualfiles.cpp
Labels: p1-urgent, PR available

#9190 [tests-only] Added more gui tests for sharing with user and group (Part 01)
  test/gui/shared/scripts/pageObjects/PublicLinkDialog.py
  test/gui/shared/scripts/pageObjects/SharingDialog.py
  test/gui/shared/steps/steps.py
  test/gui/tst_sharing/test.feature
Labels: QA:team

#9322 [Tests-Only]Skipped failing expiration tests
  test/gui/tst_sharing/test.feature
Labels: QA:team

#9320 [Tests-Only] Reverted removed steps of VFS tests
  test/gui/shared/steps/steps.py
  test/gui/tst_vfs/test.feature
Labels: QA:team

#9310 [tests-only] Cleanup test server in after scenario hook
  test/gui/shared/scripts/bdd_hooks.py
Labels: QA:team
