Repository owncloud/client, pull requests merged in 2021-03, with the labels that each got.

#8489 [DOCS] Improve Conflict Text
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/conflicts.adoc
Labels: Documentation

#8508 [tests-only]unshare without permissions to share
  test/gui/shared/scripts/names.py
  test/gui/shared/steps/steps.py
  test/gui/tst_sharing/test.feature
Labels: QA:team

#8526 Remove unnecessary stripping of leading slashes
  src/gui/folderwizard.cpp
  src/gui/selectivesyncdialog.cpp
Labels: bug
