Repository owncloud/client, pull requests merged in 2022-11, with the labels that each got.

#10261 [ocis][gui-test] Running GUI tests with oCIS server (using browser automation)
  .drone.star
  test/gui/config.sample.ini
  test/gui/drone/comment.sh
  test/gui/drone/notification_template.sh
  test/gui/drone/server.ini
  test/gui/shared/scripts/bdd_hooks.py
  test/gui/shared/scripts/helpers/SetupClientHelper.py
  test/gui/shared/scripts/helpers/WebUIHelper.py
  test/gui/shared/scripts/names.py
  test/gui/shared/scripts/pageObjects/AccountConnectionWizard.py
  test/gui/shared/scripts/pageObjects/AccountStatus.py
  test/gui/shared/steps/steps.py
  test/gui/shared/verificationPoints/VP_VFS_enabled_oCIS
  test/gui/tst_addAccount/test.feature
  test/gui/tst_sharing/test.feature
  test/gui/tst_syncing/test.feature
  test/gui/webUI/.editorconfig
  test/gui/webUI/.gitignore
  test/gui/webUI/login.spec.js
  test/gui/webUI/package.json
  test/gui/webUI/playwright.config.js
  test/gui/webUI/pnpm-lock.yaml
Labels: QA:team

#10309 Fix encoding of Gtk bookmarks
  src/common/utility_unix.cpp
Labels: Linux

#10324 [tests-only] Update oCIS version
  .drone.star
Labels: QA:team

#10325 Fix notification actions
  src/gui/activitywidget.cpp
  src/gui/notificationconfirmjob.cpp
  src/gui/notificationconfirmjob.h
  src/libsync/networkjobs/jsonjob.cpp
  src/libsync/networkjobs/jsonjob.h
Labels: p2-high
