Repository owncloud/client, pull requests merged in 2022-12, with the labels that each got.

#10340 Fix Add Space/Folder button
  changelog/unreleased/10340
  src/gui/folderstatusmodel.cpp
Labels: p2-high

#10338 Restore pre 3.0 behaviour of clearing the cookies befor a token refresh
  changelog/unreleased/10338
  src/gui/connectionvalidator.cpp
  src/libsync/creds/oauth.cpp
  src/libsync/networkjobs/checkserverjobfactory.cpp
  src/libsync/networkjobs/checkserverjobfactory.h
Labels: p2-high

#10349 Configure tx minimum percentage in config file
  translations/.tx/config
  translations/Makefile
Labels: translation

#10354 Load log file count limit properly from config file
  src/gui/application.cpp
  src/gui/logbrowser.cpp
  src/libsync/configfile.cpp
  src/libsync/configfile.h
  src/libsync/logger.cpp
Labels: bug

#10356 [gui-tests] Avoid use of names in step defs but use methods from page objects (part 1)
  test/gui/shared/scripts/names.py
  test/gui/shared/scripts/pageObjects/AccountStatus.py
  test/gui/shared/scripts/pageObjects/Toolbar.py
  test/gui/shared/steps/steps.py
  test/gui/tst_addAccount/test.feature
  test/gui/tst_removeAccountConnection/test.feature
Labels: QA:team

#10362 [gui-tests] Avoid use of names in step defs but use methods from page objects (part 2)
  test/gui/shared/scripts/names.py
  test/gui/shared/scripts/pageObjects/AccountStatus.py
  test/gui/shared/scripts/pageObjects/PublicLinkDialog.py
  test/gui/shared/scripts/pageObjects/SharingDialog.py
  test/gui/shared/scripts/pageObjects/SyncWizard.py
  test/gui/shared/steps/steps.py
Labels: QA:team

#10377 [gui-tests] Remove unwanted names or object selectors
  test/gui/shared/scripts/names.py
  test/gui/shared/scripts/pageObjects/AccountConnectionWizard.py
  test/gui/shared/scripts/pageObjects/Activity.py
  test/gui/shared/scripts/pageObjects/EnterPassword.py
  test/gui/shared/scripts/pageObjects/PublicLinkDialog.py
  test/gui/shared/scripts/pageObjects/SharingDialog.py
  test/gui/shared/scripts/pageObjects/SyncConnectionWizard.py
  test/gui/shared/steps/steps.py
Labels: QA:team

#10379 [gui-tests] Bump middleware version to v1.8.3
  .drone.star
Labels: QA:team

#10378 [gui-tests] Remove assertions from POs and When steps
  test/gui/shared/scripts/pageObjects/AccountConnectionWizard.py
  test/gui/shared/scripts/pageObjects/AccountSetting.py
  test/gui/shared/scripts/pageObjects/Activity.py
  test/gui/shared/scripts/pageObjects/EnterPassword.py
  test/gui/shared/scripts/pageObjects/PublicLinkDialog.py
  test/gui/shared/scripts/pageObjects/SharingDialog.py
  test/gui/shared/scripts/pageObjects/SyncConnection.py
  test/gui/shared/scripts/pageObjects/SyncConnectionWizard.py
  test/gui/shared/steps/steps.py
Labels: QA:team

#10381 [gui-tests] Separate steps
  test/gui/config.xml
  test/gui/shared/scripts/bdd_hooks.py
  test/gui/shared/scripts/helpers/FilesHelper.py
  test/gui/shared/scripts/helpers/SyncHelper.py
  test/gui/shared/scripts/helpers/UserHelper.py
  test/gui/shared/steps/account_context.py
  test/gui/shared/steps/file_context.py
  test/gui/shared/steps/server_context.py
  test/gui/shared/steps/sharing_context.py
  test/gui/shared/steps/steps.py
  test/gui/shared/steps/sync_context.py
  test/gui/suite.conf
Labels: QA:team
