Repository owncloud/client, pull requests merged in 2023-02, with the labels that each got.

#10438 [gui-tests] Add tests for space member with Viewer role
  test/gui/shared/scripts/helpers/FilesHelper.py
  test/gui/shared/scripts/helpers/SpaceHelper.py
  test/gui/shared/steps/spaces_context.py
  test/gui/tst_spaces/test.feature
  test/gui/tst_spaces/test.py
Labels: QA:team

#10476 Fix duplicate acct: in Webfinger resource ID
  src/libsync/creds/webfinger.cpp
Labels: bug

#10478 Fix duplicate acct: in Webfinger resource ID
  src/libsync/creds/webfinger.cpp
Labels: bug

#10475 Fix next button on Webfinger setup wizard page
  changelog/unreleased/10441
  src/gui/newwizard/pages/webfingersetupwizardpage.cpp
Labels: bug

#10488 Enable drone ci for 3.2 branch
  .drone.star
  test/gui/drone/notification_template.sh
Labels: QA:team

#10489 [ci] Upload GUI reports on failure only
  .drone.star
  test/gui/drone/notification_template.sh
Labels: QA:team

#10493 Improve wizard pages' names
  src/gui/newwizard/enums.cpp
Labels: Design & UX

#10508 [ci] Notify chat with gui reports on tag events
  .drone.star
  test/gui/drone/notification_template.sh
Labels: QA:team

#10530 [ci] Notify chat with gui reports on tag events (#10508)
  .drone.star
  test/gui/drone/notification_template.sh
Labels: QA:team

#10433 [tests-only] Added GUI test scenario to check local sync and default sync options
  test/gui/shared/scripts/pageObjects/AccountConnectionWizard.py
  test/gui/shared/steps/account_context.py
  test/gui/tst_addAccount/test.feature
Labels: QA:team

#10523 [gui-tests] Added test scenario to open log dialog
  test/gui/shared/scripts/pageObjects/AccountSetting.py
  test/gui/shared/steps/account_context.py
  test/gui/tst_checkAlltabs/test.feature
Labels: QA:team

#10457 [tests-only] add GUI test for skipping folder configuration
  test/gui/shared/scripts/pageObjects/AccountConnectionWizard.py
  test/gui/shared/steps/account_context.py
  test/gui/tst_syncing/test.feature
  test/gui/tst_syncing/verificationPoints/empty_sync_connection
Labels: QA:team
