Repository owncloud/client, pull requests merged in 2023-08, with the labels that each got.

#11105 Add changelog entry for client-desktop-vfs-win PR 19
  changelog/unreleased/client-desktop-vfs-win-19
Labels: Windows

#11095 [gui-tests][full-ci] Enable squish GUI tests
  .drone.star
  test/gui/shared/scripts/helpers/SetupClientHelper.py
  test/gui/shared/scripts/pageObjects/SyncConnectionWizard.py
  test/gui/shared/steps/sync_context.py
  test/gui/tst_sharing/test.feature
  test/gui/tst_syncing/test.feature
  test/gui/tst_syncing/verificationPoints/empty_sync_connection
Labels: QA:team

#11098 Update release_template.md
  .github/release_template.md
Labels: p2-high
