Repository owncloud/client, pull requests merged in 2023-11, with the labels that each got.

#11322 [tests-only] [full-ci] add test for verifying options of settings tab
  test/gui/shared/scripts/names.py
  test/gui/shared/scripts/pageObjects/Settings.py
  test/gui/shared/scripts/pageObjects/Toolbar.py
  test/gui/shared/steps/server_context.py
  test/gui/shared/steps/sync_context.py
  test/gui/tst_checkAlltabs/test.feature
Labels: QA:team

#11253 Remove migration of old db files
  src/common/syncjournaldb.cpp
  src/common/syncjournaldb.h
  src/gui/folderman.cpp
Labels: technical debt

#11355 [docs-only] add toc to changelog
  changelog/CHANGELOG.tmpl
Labels: Documentation

#11252 Remove custom data size formatting
  src/common/utility.cpp
  test/testutility.cpp
Labels: technical debt

#11376 Fix current CPU architecture detection with rosetta2
  src/common/utility.cpp
  src/common/utility.h
  src/common/utility_mac.mm
  src/gui/updater/updater.cpp
  src/libsync/theme.cpp
Labels: Enhancement, macOS

#11067 [full-ci][gui-tests] Extend oAuth2 scenario
  test/gui/shared/scripts/bdd_hooks.py
  test/gui/shared/scripts/helpers/SetupClientHelper.py
  test/gui/shared/scripts/helpers/SyncHelper.py
  test/gui/shared/scripts/pageObjects/AccountConnectionWizard.py
  test/gui/shared/scripts/pageObjects/AccountSetting.py
  test/gui/shared/scripts/pageObjects/EnterPassword.py
  test/gui/shared/scripts/pageObjects/Toolbar.py
  test/gui/shared/steps/account_context.py
  test/gui/shared/steps/spaces_context.py
  test/gui/tst_loginLogout/test.feature
Labels: QA:team

#11394 [tests-only] [full-ci] skip GUI tests related to suffix vfs
  test/gui/tst_addAccount/test.feature
  test/gui/tst_vfs/test.feature
Labels: QA:team

#11407 Bump oCIS version to 4
  .drone.star
Labels: QA:team
