Repository owncloud/client, pull requests merged in 2023-01, with the labels that each got.

#10384 [gui-tests] Fix date parsing
  test/gui/shared/scripts/pageObjects/PublicLinkDialog.py
Labels: QA:team

#10387 Fix opening the browser
  changelog/unreleased/10387
  src/libsync/appprovider.cpp
Labels: p2-high

#10393 [tests-only] Bump oCIS version to 2.0.0
  .drone.star
Labels: QA:team

#10401 [gui-tests] Import test module
  test/gui/shared/scripts/helpers/SyncHelper.py
  test/gui/shared/scripts/pageObjects/SharingDialog.py
  test/gui/shared/scripts/pageObjects/SyncConnectionWizard.py
Labels: QA:team

#10410 Skip `testLocalFileRemoteDirConflict()` for dehydrated files
  test/testsyncconflict.cpp
Labels: Windows

#10403 [gui-tests] Refactor sync paths for oc10 and ocis
  test/gui/shared/scripts/bdd_hooks.py
  test/gui/shared/scripts/helpers/SetupClientHelper.py
  test/gui/shared/scripts/helpers/SyncHelper.py
  test/gui/shared/scripts/pageObjects/EnterPassword.py
  test/gui/shared/scripts/pageObjects/SyncConnection.py
  test/gui/shared/scripts/pageObjects/SyncConnectionWizard.py
  test/gui/shared/steps/account_context.py
  test/gui/shared/steps/file_context.py
  test/gui/shared/steps/sharing_context.py
  test/gui/shared/steps/sync_context.py
  test/gui/suite.conf
Labels: QA:team

#10392 [tests-only] Add GUI tests related to moving files and folders
  test/gui/shared/steps/file_context.py
  test/gui/tst_moveFilesFolders/test.feature
  test/gui/tst_moveFilesFolders/test.py
Labels: QA:team

#10426 [tests-only] Add GUI test related to deleting a file and a folder
  test/gui/tst_deletFilesFolders/test.feature
Labels: QA:team

#10424 [gui-tests] Notify with gui tests reports on success
  .drone.star
  test/gui/drone/notification_template.sh
Labels: QA:team
