Repository owncloud/client, pull requests merged in 2023-07, with the labels that each got.

#11005 [CI] Remove PR-based special drone actions from CI
  .drone.star
Labels: QA:team

#11006 [CI][4] Remove special PR-based drone actions from CI
  .drone.star
Labels: QA:team

#11036 Fix folder setup
  src/gui/folderman.cpp
Labels: p1-urgent

#11027 [tests-only] [full-ci] Given step implementation for creating folder in the server
  test/gui/shared/scripts/helpers/api/webdav_helper.py
  test/gui/shared/steps/file_context.py
  test/gui/shared/steps/server_context.py
  test/gui/tst_addAccount/test.feature
  test/gui/tst_deletFilesFolders/test.feature
  test/gui/tst_moveFilesFolders/test.feature
  test/gui/tst_sharing/test.feature
  test/gui/tst_syncing/test.feature
Labels: QA:team

#11040 [tests-only] [full-ci] Upload file in server
  test/gui/shared/scripts/helpers/api/webdav_helper.py
  test/gui/shared/steps/server_context.py
  test/gui/tst_deletFilesFolders/test.feature
  test/gui/tst_editFiles/test.feature
  test/gui/tst_moveFilesFolders/test.feature
  test/gui/tst_sharing/test.feature
Labels: QA:team

#10968 Update release_template.md
  .github/release_template.md
Labels: Needs info

#11037 Fix power notification handling on macOS
  src/libsync/platform_mac.mm
Labels: macOS
