Repository owncloud/client, pull requests merged in 2024-07, with the labels that each got.

#11725 [gui-tests][full-ci] add gui test to remove folder sync connection
  test/gui/shared/scripts/names.py
  test/gui/shared/scripts/pageObjects/SyncConnection.py
  test/gui/shared/steps/account_context.py
  test/gui/shared/steps/sync_context.py
  test/gui/tst_syncing/test.feature
Labels: QA:team

#11713 [ci][full-ci] update config to use new smaller squish image
  .drone.star
Labels: QA:team

#11723 Work/a11y column sorting
  src/gui/issueswidget.cpp
  src/gui/issueswidget.h
  src/gui/protocolwidget.cpp
  src/gui/protocolwidget.h
Labels: Accessibility

#11736 [gui-tests][full-ci] Remove duplicate selectors
  test/gui/shared/scripts/pageObjects/SyncConnectionWizard.py
Labels: QA:team

#11737 [gui-tests][full-ci]update step to only check if the local folder is present in the remote destination wizard
  test/gui/shared/scripts/pageObjects/SyncConnectionWizard.py
  test/gui/shared/steps/sync_context.py
  test/gui/tst_syncing/test.feature
Labels: QA:team

#11726 [gui-tests][full-ci]add test to check the sync activity in Sync Protocal tab
  test/gui/shared/steps/sync_context.py
  test/gui/tst_syncing/test.feature
Labels: QA:team

#11324 [gui-tests][full-ci] Add multiple accounts in a single step
  test/gui/shared/scripts/helpers/SetupClientHelper.py
  test/gui/shared/scripts/helpers/SpaceHelper.py
  test/gui/shared/scripts/pageObjects/EnterPassword.py
  test/gui/shared/steps/account_context.py
  test/gui/shared/steps/spaces_context.py
  test/gui/tst_removeAccountConnection/test.feature
Labels: QA:team

#11741 Work/appimage updater dialog
  src/gui/updater/CMakeLists.txt
  src/gui/updater/appimageupdateavailabledialog.h
  src/gui/updater/appimageupdateavailablewidget.cpp
  src/gui/updater/appimageupdateavailablewidget.h
  src/gui/updater/appimageupdateavailablewidget.ui
  src/gui/updater/appimageupdater.cpp
Labels: Linux, AppImage

#11710 [gui-tests][full-ci] Added test for checking incremented number with bracket while adding new account and folder
  test/gui/envs.txt
  test/gui/shared/scripts/bdd_hooks.py
  test/gui/shared/scripts/helpers/ConfigHelper.py
  test/gui/shared/scripts/helpers/FilesHelper.py
  test/gui/shared/scripts/helpers/SetupClientHelper.py
  test/gui/shared/scripts/names.py
  test/gui/shared/scripts/pageObjects/AccountConnectionWizard.py
  test/gui/shared/scripts/pageObjects/SyncConnectionWizard.py
  test/gui/shared/steps/account_context.py
  test/gui/shared/steps/file_context.py
  test/gui/shared/steps/sync_context.py
  test/gui/tst_addAccount/test.feature
Labels: QA:team

#11735 Fix missing desktop/application icon with Wayland
  owncloud.desktop.in
Labels: Linux, AppImage

#11766 [gui-tests][full-ci] test for checking already synced spaces should not be listed in sync connection wizard
  test/gui/tst_addAccount/test.feature
Labels: QA:team

#11767 [gui-tests][full-ci]add test to check for open connection sync button to be disabled
  test/gui/shared/scripts/pageObjects/SyncConnectionWizard.py
  test/gui/shared/steps/sync_context.py
  test/gui/tst_addAccount/test.feature
  test/gui/tst_loginLogout/test.feature
Labels: QA:team
