Repository owncloud/client, pull requests merged in 2025-04, with the labels that each got.

#12127 WIP
  CMakeLists.txt
Labels: macOS

#12137 [test-only][full-ci] Refactor tests to use normal account setup flow
  test/gui/shared/scripts/helpers/SetupClientHelper.py
  test/gui/shared/scripts/helpers/SyncHelper.py
  test/gui/shared/scripts/pageObjects/SyncConnection.py
  test/gui/shared/steps/account_context.py
  test/gui/shared/steps/spaces_context.py
  test/gui/shared/steps/sync_context.py
  test/gui/tst_activity/test.feature
  test/gui/tst_sharing/test.feature
  test/gui/tst_spaces/test.feature
  test/gui/tst_syncing/test.feature
Labels: QA:team

#12150 [DC-28] fix: menu to pop up on the managed account button
  src/gui/accountsettings.cpp
  src/gui/accountsettings.h
Labels: Accessibility
