Repository owncloud/client, pull requests merged in 2025-03, with the labels that each got.

#12091 Update MacOS --> macOS where necessary, especially for the translation
  changelog/unreleased/12044.md
  src/csync/INSTALL
  src/gui/folderman.cpp
  src/gui/updater/ocupdater.h
Labels: translation

#12038 docs: update release template
  .github/release_template.md
Labels: Documentation, QA:team

#12105 Work/numeral translations en us
  translations/client_en.ts
Labels: i18n

#12117 The changelog unreleased 12045 has no .md extension
  changelog/unreleased/12045.md
Labels: Documentation
